export default {
  BFX_SOCKET_CONNECTED: 'BFX_SOCKET_CONNECTED',
  BFX_SOCKET_DISCONNECTED: 'BFX_SOCKET_DISCONNECTED',
  BFX_SOCKET_RECEIVED: 'BFX_SOCKET_RECEIVED',
  BFX_SOCKET_SUBSCRIBED: 'BFX_SOCKET_SUBSCRIBED',
  BFX_SOCKET_QUEUE: 'BFX_SOCKET_QUEUE',
  BFX_SOCKET_FLUSH: 'BFX_SOCKET_FLUSH',
  BFX_SOCKET_DISCONNECT: 'BFX_SOCKET_DISCONNECT',
};
